config/routes.rb
Rently::Application.routes.draw do
  root to: 'welcome#index'
  resources :apartments
  resource :dashboard, only: [:show]
  resources :users, only: [:create] do
    resource :favorite, only: [:create]
  end
end

app/models/apartment.rb
class Apartment < ActiveRecord::Base
  attr_accessible :address, :rent, :city, :zip, :photos_attributes, :bedrooms, :bathrooms, :state, :description

  validates :address, presence: true
  validates :rent, presence: true

  belongs_to :landlord, class_name: 'User'
  has_many :photos, dependent: :destroy
  has_many :favorites
  has_many :favorited_apartments, through: :favorites, dependent: :destroy

  accepts_nested_attributes_for :photos, allow_destroy: true
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  attr_accessible :apartment_id

  belongs_to :apartment
  belongs_to :user
end

app/models/guest.rb
class Guest
  def can_edit?(apartment)
    false
  end

  def can_favorite?(apartment)
    true
  end

  def role
    'Guest'
  end
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :photo
  belongs_to :apartment
  has_attached_file :photo, styles: { thumb: '100x100>' }
  validates_attachment :photo, presence: true,
    content_type: {content_type: ['image/jpeg', 'image/pjpeg', 'image/png', 'image/gif']}
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User

  ROLES = %w(Landlord Tenant).freeze

  attr_accessible :email, :role, :name

  validates :role, presence: true
  validates :name, presence: true

  has_many :apartments, foreign_key: "landlord_id", dependent: :destroy
  has_many :favorites
  has_many :favorited_apartments, through: :favorites, source: :apartment

  def can_edit?(apartment)
    apartment.landlord == self
  end

  def can_favorite?(apartment)
    favorites.where(apartment_id: apartment.id).empty?
  end

  def dashboard
    role.downcase
  end
end

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController

  def index
    @apartments = Apartment.all # all is bad mmkay
  end

  def new
    @apartment = Apartment.new
    5.times { @apartment.photos.build }
  end

  def create
    @apartment = current_user.apartments.new(params[:apartment])
    if @apartment.save
      redirect_to dashboard_path, notice: "Apartment Created!"
    else
      @photos = @apartment.photos
      @new_photos = 5.times.map { @apartment.photos.build }
      render :new
    end
  end

  def show
    @apartment = Apartment.find(params[:id])
  end

  def edit
    @apartment = current_user.apartments.find(params[:id])
    @photos = @apartment.photos
    @new_photos = 5.times.map { @apartment.photos.build }
  end

  def update
    @apartment = current_user.apartments.find(params[:id])
    if @apartment.update_attributes(params[:apartment])
      redirect_to [:edit, @apartment], notice: "Updated!"
    else
      render :edit
    end
  end

  def destroy
    current_user.apartments.find(params[:id]).destroy
    redirect_to dashboard_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Authentication
  protect_from_forgery

  def current_user
    super || Guest.new
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def show
  end

  def create
    current_user.favorites.create(apartment_id: params[:apartment][:id])
    redirect_to dashboard_path
  end

  def destroy
    current_user.favorites.find(params[:id]).destroy
    redirect_to dashboard_path
  end
end

app/controllers/landlords_controller.rb
class LandlordsController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/tenants_controller.rb
class TenantsController < ApplicationController
  def show
  end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
  def create
    @user = user_from_params

    if @user.save
      sign_in @user
      redirect_back_or url_after_create
    else
      render template: 'users/new'
    end
  end

  def user_from_params
    user_params = params[:user] || Hash.new
    email = user_params.delete(:email)
    password = user_params.delete(:password)
    role = user_params.delete(:role)
    name = user_params.delete(:name)

    Clearance.configuration.user_model.new(user_params).tap do |user|
      user.email = email
      user.password = password
      user.role = role
      user.name = name
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_filter :check_for_user

  def index
  end

  private

  def check_for_user
    if signed_in?
      redirect_to dashboard_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/datalist_helper.rb
module DatalistHelper
  def datalist(form, name, list)
    form.text_field(name, list: name) +
    "<datalist id=#{name}>".html_safe +
    options_for_select(list) +
    "</datalist>".html_safe
  end
end

app/helpers/states_helper.rb
module StatesHelper
  def us_states
      [
        ['Alabama', 'AL'],
        ['Alaska', 'AK'],
        ['Arizona', 'AZ'],
        ['Arkansas', 'AR'],
        ['California', 'CA'],
        ['Colorado', 'CO'],
        ['Connecticut', 'CT'],
        ['Delaware', 'DE'],
        ['District of Columbia', 'DC'],
        ['Florida', 'FL'],
        ['Georgia', 'GA'],
        ['Hawaii', 'HI'],
        ['Idaho', 'ID'],
        ['Illinois', 'IL'],
        ['Indiana', 'IN'],
        ['Iowa', 'IA'],
        ['Kansas', 'KS'],
        ['Kentucky', 'KY'],
        ['Louisiana', 'LA'],
        ['Maine', 'ME'],
        ['Maryland', 'MD'],
        ['Massachusetts', 'MA'],
        ['Michigan', 'MI'],
        ['Minnesota', 'MN'],
        ['Mississippi', 'MS'],
        ['Missouri', 'MO'],
        ['Montana', 'MT'],
        ['Nebraska', 'NE'],
        ['Nevada', 'NV'],
        ['New Hampshire', 'NH'],
        ['New Jersey', 'NJ'],
        ['New Mexico', 'NM'],
        ['New York', 'NY'],
        ['North Carolina', 'NC'],
        ['North Dakota', 'ND'],
        ['Ohio', 'OH'],
        ['Oklahoma', 'OK'],
        ['Oregon', 'OR'],
        ['Pennsylvania', 'PA'],
        ['Puerto Rico', 'PR'],
        ['Rhode Island', 'RI'],
        ['South Carolina', 'SC'],
        ['South Dakota', 'SD'],
        ['Tennessee', 'TN'],
        ['Texas', 'TX'],
        ['Utah', 'UT'],
        ['Vermont', 'VT'],
        ['Virginia', 'VA'],
        ['Washington', 'WA'],
        ['West Virginia', 'WV'],
        ['Wisconsin', 'WI'],
        ['Wyoming', 'WY']
      ].map { |list| list[0] }
  end
end

app/views/apartments/_form.html.erb
<%= form_for @apartment do |f| %>
  <li>
    <%= f.label :address %>
    <%= f.text_field :address %>
  </li>
  <li>
    <%= f.label :city %>
    <%= f.text_field :city %>
  </li>
  <li>
    <%= f.label :zip %>
    <%= f.text_field :zip %>
  </li>
  <li>
    <%= f.label :state %>
    <%= datalist f, :state, us_states %>
  </li>
  <li>
    <%= f.label :rent %>
    <%= f.text_field :rent %>
  </li>
  <li>
    <%= f.label :bedrooms %>
    <%= f.text_field :bedrooms %>
  </li>
  <li>
    <%= f.label :bathrooms %>
    <%= f.text_field :bathrooms %>
  </li>
  <li>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </li>
  <li>
    <%= f.fields_for :photos, @new_photos do |photo| %>
      <%= photo.label :photo %>
      <%= photo.file_field :photo %>
    <% end -%>
  </li>
  <li>
    <%= submit_tag 'submit' %>
  </li>
<% end -%>

app/views/apartments/edit.html.erb
<% if @apartment.errors.any? -%>
  <% @apartment.errors.full_messages.each do |error| -%>
    <%= error %>
  <% end -%>
<% end -%>
<%= render 'form' %>

app/views/apartments/index.html.erb
<ul>
<% @apartments.each do |apartment| -%>
  <li>
    <%= link_to apartment.address, apartment %>
    <%= apartment.rent %>
  </li>
<% end -%>
</ul>

app/views/apartments/new.html.erb
<h2>Create a New Apartment Listing</h2>
<%= render 'form' %>

app/views/apartments/show.html.erb
<%= @apartment.address %>
<%= @apartment.rent %>
<%= @apartment.landlord.name %>
<% if current_user.can_edit?(@apartment) %>
  <%= link_to "edit", edit_apartment_path %>
<% end -%>
<% if current_user.can_favorite?(@apartment) %>
  <%= render "favorites/#{current_user.role.downcase}" %>
<% end -%>
<% @apartment.photos.each do |photo| %>
  <%= image_tag photo.photo.url(:thumb) %>
<% end -%>

app/views/dashboards/_landlord.html.erb
<h2>Your Listed Apartments</h2>
<%= link_to "Create a new Listing", new_apartment_path %><br />
<ul>
  <% current_user.apartments.each do |apartment| %>
    <li>
      <%= link_to apartment.address, apartment %>
      <%= "$#{apartment.rent}" %>
    </li>
  <% end -%>
</ul>

app/views/dashboards/_tenant.html.erb
<h2>Your Favorites</h2>
<ul>
  <% current_user.favorites.each do |fav| -%>
    <li>
      <%= link_to fav.apartment.address, apartment_path(fav.apartment_id) %>
      <%= link_to "delete favorite", "#{current_user.id}/favorites/#{fav.id}", method: :delete %>
    </li>
  <% end -%>
</ul>

app/views/dashboards/show.html.erb
<%= render current_user.dashboard %>

app/views/favorites/_guest.html.erb
<%= button_to 'favorite', sign_up_path %>

app/views/favorites/_tenant.html.erb
<%= form_for Favorite.new, url: user_favorite_path(current_user) do |f| %>
  <%= hidden_field :apartment, :id %>
  <%= f.submit 'favorite' %>
<% end %>

app/views/landlords/show.html.erb
<h2>Your Listed Apartments</h2>
<%= link_to "Create a new Listing", new_apartment_path %><br />
<% @landlord.apartments.each do |apartment| %>
  <%= link_to apartment.address, apartment %>
  <%= "$#{apartment.rent}" %>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tag %>
  <title>Rently | Renters and Landlords</title>
</head>
<body>
  <div id="header">
    <h1>Rently - A Place for Renters and Landlords to Connect</h1>
    <% if signed_in? -%>
      <%= link_to "Sign out", sign_out_path, :method => :delete %>
      Welcome <%= link_to current_user.name, dashboard_path %>
    <% else -%>
      <%= link_to "Sign in", sign_in_path %>
      <%= link_to "Sign up", sign_up_path %>
    <% end -%>
  </div>
  <div id="flash">
    <% flash.each do |key, value| -%>
      <div id="flash_<%= key %>"><%= value %></div>
    <% end %>
  </div>
  <%= yield %>
</body>
</html>

app/views/tenants/show.html.erb
<h2>Your Favorites</h2>
<% @tenant.favorited_apartments.each do |apartment| -%>
  <%= link_to apartment.address, apartment_path(apartment_id) %>
  <%= link_to "delete favorite", "#{current_user.id}/favorites/#{fav.id}", method: :delete %>
<% end -%>

app/views/users/_form.html.erb
<div class="text_field">
  <%= form.label :name %>
  <%= form.text_field :name %>
</div>
<div class="text_field">
  <%= form.label :email %>
  <%= form.text_field :email, :type => "email" %>
</div>
<div class="password_field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>
<div class="select_field">
  <%= form.label :role %>
  <%= form.select :role, User::ROLES %>
</div>

app/views/users/new.html.erb
<h2>Sign up</h2>

<%= form_for @user do |form| %>
  <%= render :partial => '/users/form', :object => form %>
  <%= form.submit 'Sign up' %>
<% end %>

app/views/welcome/index.html.erb
<p>This is the home page</p>